/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nightfall.project;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Player gracz = new Player();
        Game gameob = new Game();
        Inventory ekwipunekgracza = new Inventory();


        FileReader pliczek = null;
        String linia;
        try {
            pliczek = new FileReader("menu/asc.txt");
        } catch (FileNotFoundException e) {
            System.out.println("Blad wczytywania pliku menu/asc.txt");
            System.exit(1);
        }

        BufferedReader bpliczek = new BufferedReader(pliczek);

        try {
            while ((linia = bpliczek.readLine()) != null) {
                System.out.println(linia);
            }
        } catch (IOException e) {
            System.out.println("Blad odczytu pliku menu/asc.txt");
            System.exit(1);
        }
        Scanner wybor = new Scanner(System.in);
        boolean czywybranodobraopcje = true;
        while (czywybranodobraopcje) {
            try {
                pliczek = new FileReader("menu/asc2.txt");
            } catch (FileNotFoundException e) {
                System.out.println("Blad wczytywania pliku menu/asc2.txt");
                System.exit(1);
            }

            BufferedReader bpliczek2 = new BufferedReader(pliczek);

            try {
                while ((linia = bpliczek2.readLine()) != null) {
                    System.out.println(linia);
                }
            } catch (IOException e) {
                System.out.println("Blad odczytywania pliku menu/asc.txt");
                System.exit(1);
            }
            String wybint;
            wybint = wybor.nextLine();
            int wybint2 = Integer.parseInt(wybint);
            switch (wybint2) {
                case 1:
                    gameob.rozpocznijgre(gracz, ekwipunekgracza);
                    czywybranodobraopcje = false;
                case 2:
                    FileReader plikautor = null;
                    String liniaautor;
                    try {
                        plikautor = new FileReader("menu/autorzy");
                    } catch (FileNotFoundException e) {
                        System.out.println("Blad wczytywania pliku menu/autorzy");
                        System.exit(1);
                    }

                    BufferedReader bautor = new BufferedReader(plikautor);

                    try {
                        while ((liniaautor = bautor.readLine()) != null) {
                            System.out.println(liniaautor);
                        }
                    } catch (IOException e) {
                        System.out.println("Blad odczyty pliku autorzy");
                        System.exit(1);
                    }
                    break;
                case 3:
                    System.exit(1);
                case 69:
                    FileReader gachiplik = null;
                    String gachlinia;
                    try {
                        gachiplik = new FileReader("menu/easteregg");
                    } catch (FileNotFoundException e) {
                        System.out.println("Blad odczyty pliku menu/easteregg");
                        System.exit(1);
                    }

                    BufferedReader gachibuffer = new BufferedReader(gachiplik);

                    try {
                        while ((gachlinia = gachibuffer.readLine()) != null) {
                            System.out.println(gachlinia);
                        }
                    } catch (IOException e) {
                        System.out.println("Blad wczytania pliku menu/easteregg");
                        System.exit(1);
                    }
                default:
                    System.out.println("Niepoprawny numer");

            }
        }
    }
}